title: HyperCTF
description: HyperCTF is a Capture-The-Flag cybersecurity competition that is run by three high school students. Our goal for this Capture-The-Flag cybersecurity competition is to give aspiring cybersecurity engineers the tools and skills necessary to be able to enter that field of cybersecurity.
